service: msteams-reminders
provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  profile: custom-profile
  role: arn:aws:iam::077508673229:role/LambdaDynamoDBAccess
functions:
  process:
    handler: msteams-reminders-process.handler
    timeout: 60
    tags:
      Description: "Queries DynamoDB for reminders and posts to Teams"
      Owner: "John Sibly"
    events:
      - schedule: cron(0/5 * * * ? *)
  put:
    handler: msteams-reminders-put.handler
    timeout: 60
    tags:
      Description: "Adds a reminder to DynamoDB"
      Owner: "John Sibly"
  get:
    handler: msteams-reminders-get.handler
    timeout: 60
    tags:
      Description: "Queries for reminders omitting teamsChannelWebhook"
      Owner: "John Sibly"
  delete:
    handler: msteams-reminders-delete.handler
    timeout: 60
    tags:
      Description: "Deletes the reminder specified by the id"
      Owner: "John Sibly"

